# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-16 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={},
        ),
    ]
